CREATE TABLE conversation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id        BIGINT                                  NOT NULL,
    post_owner_id  BIGINT                                  NOT NULL,
    participant_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_conversation PRIMARY KEY (id)
);

CREATE TABLE conversation_message
(
    conversation_entity_id BIGINT NOT NULL,
    message_id             BIGINT NOT NULL
);

CREATE TABLE message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id    BIGINT                                  NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_displayed BOOLEAN                                 NOT NULL,
    message      BIGINT,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE conversation_message
    ADD CONSTRAINT uc_conversation_message_message UNIQUE (message_id);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_MESSAGE FOREIGN KEY (message) REFERENCES conversation (id);

ALTER TABLE conversation_message
    ADD CONSTRAINT fk_conmes_on_conversation_entity FOREIGN KEY (conversation_entity_id) REFERENCES conversation (id);

ALTER TABLE conversation_message
    ADD CONSTRAINT fk_conmes_on_message_entity FOREIGN KEY (message_id) REFERENCES message (id);