/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gametrader.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.gametrader.api.model.MessageEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConversationDto
 */
public class ConversationDtoTest {
    private final ConversationDto model = new ConversationDto();

    /**
     * Model tests for ConversationDto
     */
    @Test
    public void testConversationDto() {
        // TODO: test ConversationDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'postId'
     */
    @Test
    public void postIdTest() {
        // TODO: test postId
    }

    /**
     * Test the property 'postOwnerId'
     */
    @Test
    public void postOwnerIdTest() {
        // TODO: test postOwnerId
    }

    /**
     * Test the property 'participantId'
     */
    @Test
    public void participantIdTest() {
        // TODO: test participantId
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
