/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gametrader.api;

import com.gametrader.api.model.ConversationDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChatControllerApi
 */
@Ignore
public class ChatControllerApiTest {

    private final ChatControllerApi api = new ChatControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createConversationTest() {
        ConversationDto conversationDto = null;
        ConversationDto response = api.createConversation(conversationDto);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConversationByIdTest() {
        Long id = null;
        ConversationDto response = api.getConversationById(id);

        // TODO: test validations
    }
    
}
